name: Without jQuery
title:  Learn Javascript with code examples to replace jQuery
baseurl: /without-jquery
highlighter: kramdown
kramdown:
  input: GFM
sass:
    sass_dir: _sass
exclude: [
  "help.hbs",
  "scraper.js",
  "method",
  "working.js",
  "vendor",
  "javascripts",
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "bower_components"
]

include: [
  "readme"
]
