module.exports = [
    {href: "docs/add.html", title: ".add()",
        description: "Add elements to the set of matched elements."},
    {href: "docs/addBack.html", title: ".addBack()",
        description: "Add the previous set of elements on the stack to the current set, optionally filtered by a selector."},
    {href: "docs/addClass.html", title: ".addClass()",
        description: "Adds the specified class(es) to each of the set of matched elements."},
    {href: "docs/after.html", title: ".after()",
        description: "Insert content, specified by the parameter, after each element in the set of matched elements."},
    {href: "docs/ajaxComplete.html", title: ".ajaxComplete()",
        description: "Register a handler to be called when Ajax requests complete. This is an AjaxEvent."},
    {href: "docs/ajaxError.html", title: ".ajaxError()",
        description: "Register a handler to be called when Ajax requests complete with an error. This is an Ajax Event."},
    {href: "docs/ajaxSend.html", title: ".ajaxSend()",
        description: "Attach a function to be executed before an Ajax request is sent. This is an Ajax Event."},
    {href: "docs/ajaxStart.html", title: ".ajaxStart()",
        description: "Register a handler to be called when the first Ajax request begins. This is an Ajax Event."},
    {href: "docs/ajaxStop.html", title: ".ajaxStop()",
        description: "Register a handler to be called when all Ajax requests have completed. This is an Ajax Event."},
    {href: "docs/ajaxSuccess.html", title: ".ajaxSuccess()",
        description: "Attach a function to be executed whenever an Ajax request completes successfully. This is an Ajax Event."},
    {href: "docs/all-selector.html", title: "All Selector (“*”)",
        description: "Selects all elements."},
    {href: "docs/andSelf.html", title: ".andSelf()",
        description: "Add the previous set of elements on the stack to the current set."},
    {href: "docs/animate.html", title: ".animate()",
        description: "Perform a custom animation of a set of CSS properties."},
    {href: "docs/animated-selector.html", title: ":animated Selector",
        description: "Select all elements that are in the progress of an animation at the time the selector is run."},
    {href: "docs/append.html", title: ".append()",
        description: "Insert content, specified by the parameter, to the end of each element in the set of matched elements."},
    {href: "docs/appendTo.html", title: ".appendTo()",
        description: "Insert every element in the set of matched elements to the end of the target."},
    {href: "docs/attr.html", title: ".attr()",
        description: "Get the value of an attribute for the first element in the set of matched elements or set one or more attributes for every matched element."},
    {href: "docs/attribute-contains-prefix-selector.html", title: "Attribute Contains Prefix Selector [name|=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value either equal to a given string or starting with that string followed by a hyphen (-)."},
    {href: "docs/attribute-contains-selector.html", title: "Attribute Contains Selector [name*=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value containing a given substring."},
    {href: "docs/attribute-contains-word-selector.html", title: "Attribute Contains Word Selector [name~=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value containing a given word, delimited by spaces."},
    {href: "docs/attribute-ends-with-selector.html", title: "Attribute Ends With Selector [name$=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value ending exactly with a given string. The comparison is case sensitive."},
    {href: "docs/attribute-equals-selector.html", title: "Attribute Equals Selector [name=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value exactly equal to a certain value."},
    {href: "docs/attribute-not-equal-selector.html", title: "Attribute Not Equal Selector [name!=&quot;value&quot;]",
        description: "Select elements that either don’t have the specified attribute, or do have the specified attribute but not with a certain value."},
    {href: "docs/attribute-starts-with-selector.html", title: "Attribute Starts With Selector [name^=&quot;value&quot;]",
        description: "Selects elements that have the specified attribute with a value beginning exactly with a given string."},
    {href: "docs/before.html", title: ".before()",
        description: "Insert content, specified by the parameter, before each element in the set of matched elements."},
    {href: "docs/bind.html", title: ".bind()",
        description: "Attach a handler to an event for the elements."},
    {href: "docs/blur.html", title: ".blur()",
        description: "Bind an event handler to the “blur” JavaScript event, or trigger that event on an element."},
    {href: "docs/button-selector.html", title: ":button Selector",
        description: "Selects all button elements and elements of type button."},
    {href: "docs/callbacks.add.html", title: "callbacks.add()",
        description: "Add a callback or a collection of callbacks to a callback list."},
    {href: "docs/callbacks.disable.html", title: "callbacks.disable()",
        description: "Disable a callback list from doing anything more."},
    {href: "docs/callbacks.disabled.html", title: "callbacks.disabled()",
        description: "Determine if the callbacks list has been disabled."},
    {href: "docs/callbacks.empty.html", title: "callbacks.empty()",
        description: "Remove all of the callbacks from a list."},
    {href: "docs/callbacks.fire.html", title: "callbacks.fire()",
        description: "Call all of the callbacks with the given arguments"},
    {href: "docs/callbacks.fired.html", title: "callbacks.fired()",
        description: "Determine if the callbacks have already been called at least once."},
    {href: "docs/callbacks.fireWith.html", title: "callbacks.fireWith()",
        description: "Call all callbacks in a list with the given context and arguments."},
    {href: "docs/callbacks.has.html", title: "callbacks.has()",
        description: "Determine whether a supplied callback is in a list"},
    {href: "docs/callbacks.lock.html", title: "callbacks.lock()",
        description: "Lock a callback list in its current state."},
    {href: "docs/callbacks.locked.html", title: "callbacks.locked()",
        description: "Determine if the callbacks list has been locked."},
    {href: "docs/callbacks.remove.html", title: "callbacks.remove()",
        description: "Remove a callback or a collection of callbacks from a callback list."},
    {href: "docs/change.html", title: ".change()",
        description: "Bind an event handler to the “change” JavaScript event, or trigger that event on an element."},
    {href: "docs/checkbox-selector.html", title: ":checkbox Selector",
        description: "Selects all elements of type checkbox."},
    {href: "docs/checked-selector.html", title: ":checked Selector",
        description: "Matches all elements that are checked or selected."},
    {href: "docs/child-selector.html", title: "Child Selector (“parent > child”)",
        description: "Selects all direct child elements specified by “child” of elements specified by “parent”."},
    {href: "docs/children.html", title: ".children()",
        description: "Get the children of each element in the set of matched elements, optionally filtered by a selector."},
    {href: "docs/class-selector.html", title: "Class Selector (“.class”)",
        description: "Selects all elements with the given class."},
    {href: "docs/clearQueue.html", title: ".clearQueue()",
        description: "Remove from the queue all items that have not yet been run."},
    {href: "docs/click.html", title: ".click()",
        description: "Bind an event handler to the “click” JavaScript event, or trigger that event on an element."},
    {href: "docs/clone.html", title: ".clone()",
        description: "Create a deep copy of the set of matched elements."},
    {href: "docs/closest.html", title: ".closest()",
        description: "For each element in the set, get the first element that matches the selector by testing the element itself and traversing up through its ancestors in the DOM tree."},
    {href: "docs/contains-selector.html", title: ":contains() Selector",
        description: "Select all elements that contain the specified text."},
    {href: "docs/contents.html", title: ".contents()",
        description: "Get the children of each element in the set of matched elements, including text and comment nodes."},
    {href: "docs/context.html", title: ".context",
        description: "The DOM node context originally passed to jQuery(); if none was passed then context will likely be the document."},
    {href: "docs/css.html", title: ".css()",
        description: "Get the value of a style property for the first element in the set of matched elements or set one or more CSS properties for every matched element."},
    {href: "docs/data.html", title: ".data()",
        description: "Store arbitrary data associated with the matched elements or return the value at the named data store for the first element in the set of matched elements."},
    {href: "docs/dblclick.html", title: ".dblclick()",
        description: "Bind an event handler to the “dblclick” JavaScript event, or trigger that event on an element."},
    {href: "docs/deferred.always.html", title: "deferred.always()",
        description: "Add handlers to be called when the Deferred object is either resolved or rejected."},
    {href: "docs/deferred.done.html", title: "deferred.done()",
        description: "Add handlers to be called when the Deferred object is resolved."},
    {href: "docs/deferred.fail.html", title: "deferred.fail()",
        description: "Add handlers to be called when the Deferred object is rejected."},
    {href: "docs/deferred.isRejected.html", title: "deferred.isRejected()",
        description: "Determine whether a Deferred object has been rejected."},
    {href: "docs/deferred.isResolved.html", title: "deferred.isResolved()",
        description: "Determine whether a Deferred object has been resolved."},
    {href: "docs/deferred.notify.html", title: "deferred.notify()",
        description: "Call the progressCallbacks on a Deferred object with the given args."},
    {href: "docs/deferred.notifyWith.html", title: "deferred.notifyWith()",
        description: "Call the progressCallbacks on a Deferred object with the given context and args."},
    {href: "docs/deferred.pipe.html", title: "deferred.pipe()",
        description: "Utility method to filter and/or chain Deferreds."},
    {href: "docs/deferred.progress.html", title: "deferred.progress()",
        description: "Add handlers to be called when the Deferred object generates progress notifications."},
    {href: "docs/deferred.promise.html", title: "deferred.promise()",
        description: "Return a Deferred’s Promise object."},
    {href: "docs/deferred.reject.html", title: "deferred.reject()",
        description: "Reject a Deferred object and call any failCallbacks with the given args."},
    {href: "docs/deferred.rejectWith.html", title: "deferred.rejectWith()",
        description: "Reject a Deferred object and call any failCallbacks with the given context and args."},
    {href: "docs/deferred.resolve.html", title: "deferred.resolve()",
        description: "Resolve a Deferred object and call any doneCallbacks with the given args."},
    {href: "docs/deferred.resolveWith.html", title: "deferred.resolveWith()",
        description: "Resolve a Deferred object and call any doneCallbacks with the given context and args."},
    {href: "docs/deferred.state.html", title: "deferred.state()",
        description: "Determine the current state of a Deferred object."},
    {href: "docs/deferred.then.html", title: "deferred.then()",
        description: "Add handlers to be called when the Deferred object is resolved, rejected, or still in progress."},
    {href: "docs/delay.html", title: ".delay()",
        description: "Set a timer to delay execution of subsequent items in the queue."},
    {href: "docs/delegate.html", title: ".delegate()",
        description: "Attach a handler to one or more events for all elements that match the selector, now or in the future, based on a specific set of root elements."},
    {href: "docs/dequeue.html", title: ".dequeue()",
        description: "Execute the next function on the queue for the matched elements."},
    {href: "docs/descendant-selector.html", title: "Descendant Selector (“ancestor descendant”)",
        description: "Selects all elements that are descendants of a given ancestor."},
    {href: "docs/detach.html", title: ".detach()",
        description: "Remove the set of matched elements from the DOM."},
    {href: "docs/die.html", title: ".die()",
        description: "Remove event handlers previously attached using .live() from the elements."},
    {href: "docs/disabled-selector.html", title: ":disabled Selector",
        description: "Selects all elements that are disabled."},
    {href: "docs/each.html", title: ".each()",
        description: "Iterate over a jQuery object, executing a function for each matched element."},
    {href: "docs/element-selector.html", title: "Element Selector (“element”)",
        description: "Selects all elements with the given tag name."},
    {href: "docs/empty.html", title: ".empty()",
        description: "Remove all child nodes of the set of matched elements from the DOM."},
    {href: "docs/empty-selector.html", title: ":empty Selector",
        description: "Select all elements that have no children (including text nodes)."},
    {href: "docs/enabled-selector.html", title: ":enabled Selector",
        description: "Selects all elements that are enabled."},
    {href: "docs/end.html", title: ".end()",
        description: "End the most recent filtering operation in the current chain and return the set of matched elements to its previous state."},
    {href: "docs/eq.html", title: ".eq()",
        description: "Reduce the set of matched elements to the one at the specified index."},
    {href: "docs/eq-selector.html", title: ":eq() Selector",
        description: "Select the element at index n within the matched set."},
    {href: "docs/error.html", title: ".error()",
        description: "Bind an event handler to the “error” JavaScript event."},
    {href: "docs/even-selector.html", title: ":even Selector",
        description: "Selects even elements, zero-indexed.  See also odd."},
    {href: "docs/event.currentTarget.html", title: "event.currentTarget",
        description: "The current DOM element within the event bubbling phase."},
    {href: "docs/event.data.html", title: "event.data",
        description: "An optional object of data passed to an event method when the current executing handler is bound."},
    {href: "docs/event.delegateTarget.html", title: "event.delegateTarget",
        description: "The element where the currently-called jQuery event handler was attached."},
    {href: "docs/event.isDefaultPrevented.html", title: "event.isDefaultPrevented()",
        description: "Returns whether event.preventDefault() was ever called on this event object."},
    {href: "docs/event.isImmediatePropagationStopped.html", title: "event.isImmediatePropagationStopped()",
        description: "Returns whether event.stopImmediatePropagation() was ever called on this event object."},
    {href: "docs/event.isPropagationStopped.html", title: "event.isPropagationStopped()",
        description: "Returns whether event.stopPropagation() was ever called on this event object."},
    {href: "docs/event.metaKey.html", title: "event.metaKey",
        description: "Indicates whether the META key was pressed when the event fired."},
    {href: "docs/event.namespace.html", title: "event.namespace",
        description: "The namespace specified when the event was triggered."},
    {href: "docs/event.pageX.html", title: "event.pageX",
        description: "The mouse position relative to the left edge of the document."},
    {href: "docs/event.pageY.html", title: "event.pageY",
        description: "The mouse position relative to the top edge of the document."},
    {href: "docs/event.preventDefault.html", title: "event.preventDefault()",
        description: "If this method is called, the default action of the event will not be triggered."},
    {href: "docs/event.relatedTarget.html", title: "event.relatedTarget",
        description: "The other DOM element involved in the event, if any."},
    {href: "docs/event.result.html", title: "event.result",
        description: "The last value returned by an event handler that was triggered by this event, unless the value was undefined."},
    {href: "docs/event.stopImmediatePropagation.html", title: "event.stopImmediatePropagation()",
        description: "Keeps the rest of the handlers from being executed and prevents the event from bubbling up the DOM tree."},
    {href: "docs/event.stopPropagation.html", title: "event.stopPropagation()",
        description: "Prevents the event from bubbling up the DOM tree, preventing any parent handlers from being notified of the event."},
    {href: "docs/event.target.html", title: "event.target",
        description: "The DOM element that initiated the event."},
    {href: "docs/event.timeStamp.html", title: "event.timeStamp",
        description: "The difference in milliseconds between the time the browser created the event and January 1, 1970."},
    {href: "docs/event.type.html", title: "event.type",
        description: "Describes the nature of the event."},
    {href: "docs/event.which.html", title: "event.which",
        description: "For key or mouse events, this property indicates the specific key or button that was pressed."},
    {href: "docs/fadeIn.html", title: ".fadeIn()",
        description: "Display the matched elements by fading them to opaque."},
    {href: "docs/fadeOut.html", title: ".fadeOut()",
        description: "Hide the matched elements by fading them to transparent."},
    {href: "docs/fadeTo.html", title: ".fadeTo()",
        description: "Adjust the opacity of the matched elements."},
    {href: "docs/fadeToggle.html", title: ".fadeToggle()",
        description: "Display or hide the matched elements by animating their opacity."},
    {href: "docs/file-selector.html", title: ":file Selector",
        description: "Selects all elements of type file."},
    {href: "docs/filter.html", title: ".filter()",
        description: "Reduce the set of matched elements to those that match the selector or pass the function’s test."},
    {href: "docs/finish.html", title: ".finish()",
        description: "Stop the currently-running animation, remove all queued animations, and complete all animations for the matched elements."},
    {href: "docs/first.html", title: ".first()",
        description: "Reduce the set of matched elements to the first in the set."},
    {href: "docs/first-child-selector.html", title: ":first-child Selector",
        description: "Selects all elements that are the first child of their parent."},
    {href: "docs/first-of-type-selector.html", title: ":first-of-type Selector",
        description: "Selects all elements that are the first among siblings of the same element name."},
    {href: "docs/first-selector.html", title: ":first Selector",
        description: "Selects the first matched element."},
    {href: "docs/focus.html", title: ".focus()",
        description: "Bind an event handler to the “focus” JavaScript event, or trigger that event on an element."},
    {href: "docs/focus-selector.html", title: ":focus Selector",
        description: "Selects element if it is currently focused."},
    {href: "docs/focusin.html", title: ".focusin()",
        description: "Bind an event handler to the “focusin” event."},
    {href: "docs/focusout.html", title: ".focusout()",
        description: "Bind an event handler to the “focusout” JavaScript event."},
    {href: "docs/get.html", title: ".get()",
        description: "Retrieve the DOM elements matched by the jQuery object."},
    {href: "docs/gt-selector.html", title: ":gt() Selector",
        description: "Select all elements at an index greater than index within the matched set."},
    {href: "docs/has.html", title: ".has()",
        description: "Reduce the set of matched elements to those that have a descendant that matches the selector or DOM element."},
    {href: "docs/has-attribute-selector.html", title: "Has Attribute Selector [name]",
        description: "Selects elements that have the specified attribute, with any value."},
    {href: "docs/has-selector.html", title: ":has() Selector",
        description: "Selects elements which contain at least one element that matches the specified selector."},
    {href: "docs/hasClass.html", title: ".hasClass()",
        description: "Determine whether any of the matched elements are assigned the given class."},
    {href: "docs/header-selector.html", title: ":header Selector",
        description: "Selects all elements that are headers, like h1, h2, h3 and so on."},
    {href: "docs/height.html", title: ".height()",
        description: "Get the current computed height for the first element in the set of matched elements or set the height of every matched element."},
    {href: "docs/hidden-selector.html", title: ":hidden Selector",
        description: "Selects all elements that are hidden."},
    {href: "docs/hide.html", title: ".hide()",
        description: "Hide the matched elements."},
    {href: "docs/hover.html", title: ".hover()",
        description: "Bind one or two handlers to the matched elements, to be executed when the mouse pointer enters and leaves the elements."},
    {href: "docs/html.html", title: ".html()",
        description: "Get the HTML contents of the first element in the set of matched elements or set the HTML contents of every matched element."},
    {href: "docs/id-selector.html", title: "ID Selector (“#id”)",
        description: "Selects a single element with the given id attribute."},
    {href: "docs/image-selector.html", title: ":image Selector",
        description: "Selects all elements of type image."},
    {href: "docs/index.html", title: ".index()",
        description: "Search for a given element from among the matched elements."},
    {href: "docs/innerHeight.html", title: ".innerHeight()",
        description: "Get the current computed height for the first element in the set of matched elements, including padding but not border."},
    {href: "docs/innerWidth.html", title: ".innerWidth()",
        description: "Get the current computed inner width (including padding but not border) for the first element in the set of matched elements or set the inner width of every matched element."},
    {href: "docs/input-selector.html", title: ":input Selector",
        description: "Selects all input, textarea, select and button elements."},
    {href: "docs/insertAfter.html", title: ".insertAfter()",
        description: "Insert every element in the set of matched elements after the target."},
    {href: "docs/insertBefore.html", title: ".insertBefore()",
        description: "Insert every element in the set of matched elements before the target."},
    {href: "docs/is.html", title: ".is()",
        description: "Check the current matched set of elements against a selector, element, or jQuery object and return true if at least one of these elements matches the given arguments."},
    {href: "docs/jQuery.html", title: "jQuery()",
        description: "Return a collection of matched elements either found in the DOM based on passed argument(s) or created by passing an HTML string."},
    {href: "docs/jquery-2.html", title: ".jquery",
        description: "A string containing the jQuery version number."},
    {href: "docs/jQuery.ajax.html", title: "jQuery.ajax()",
        description: "Perform an asynchronous HTTP (Ajax) request."},
    {href: "docs/jQuery.ajaxPrefilter.html", title: "jQuery.ajaxPrefilter()",
        description: "Handle custom Ajax options or modify existing options before each request is sent and before they are processed by $.ajax()."},
    {href: "docs/jQuery.ajaxSetup.html", title: "jQuery.ajaxSetup()",
        description: "Set default values for future Ajax requests. Its use is not recommended."},
    {href: "docs/jQuery.ajaxTransport.html", title: "jQuery.ajaxTransport()",
        description: "Creates an object that handles the actual transmission of Ajax data."},
    {href: "docs/jQuery.boxModel.html", title: "jQuery.boxModel",
        description: "States if the current page, in the user’s browser, is being rendered using the W3C CSS Box Model. This property was removed in jQuery 1.8. Please try to use feature detection instead."},
    {href: "docs/jQuery.browser.html", title: "jQuery.browser",
        description: "Contains flags for the useragent, read from navigator.userAgent. This property was removed in jQuery 1.9 and is available only through the jQuery.migrate plugin. Please try to use feature detection instead."},
    {href: "docs/jQuery.Callbacks.html", title: "jQuery.Callbacks()",
        description: "A multi-purpose callbacks list object that provides a powerful way to manage callback lists."},
    {href: "docs/jQuery.contains.html", title: "jQuery.contains()",
        description: "Check to see if a DOM element is a descendant of another DOM element."},
    {href: "docs/jQuery.cssHooks.html", title: "jQuery.cssHooks",
        description: "Hook directly into jQuery to override how particular CSS properties are retrieved or set, normalize CSS property naming, or create custom properties."},
    {href: "docs/jQuery.data.html", title: "jQuery.data()",
        description: "Store arbitrary data associated with the specified element and/or return the value that was set."},
    {href: "docs/jQuery.Deferred.html", title: "jQuery.Deferred()",
        description: "A constructor function that returns a chainable utility object with methods to register multiple callbacks into callback queues, invoke callback queues, and relay the success or failure state of any synchronous or asynchronous function."},
    {href: "docs/jQuery.dequeue.html", title: "jQuery.dequeue()",
        description: "Execute the next function on the queue for the matched element."},
    {href: "docs/jQuery.each.html", title: "jQuery.each()",
        description: "A generic iterator function, which can be used to seamlessly iterate over both objects and arrays. Arrays and array-like objects with a length property (such as a function’s arguments object) are iterated by numeric index, from 0 to length-1. Other objects are iterated via their named properties."},
    {href: "docs/jQuery.error.html", title: "jQuery.error()",
        description: "Takes a string and throws an exception containing it."},
    {href: "docs/jQuery.extend.html", title: "jQuery.extend()",
        description: "Merge the contents of two or more objects together into the first object."},
    {href: "docs/jQuery.fn.extend.html", title: "jQuery.fn.extend()",
        description: "Merge the contents of an object onto the jQuery prototype to provide new jQuery instance methods."},
    {href: "docs/jQuery.fx.interval.html", title: "jQuery.fx.interval",
        description: "The rate (in milliseconds) at which animations fire."},
    {href: "docs/jQuery.fx.off.html", title: "jQuery.fx.off",
        description: "Globally disable all animations."},
    {href: "docs/jQuery.get.html", title: "jQuery.get()",
        description: "Load data from the server using a HTTP GET request."},
    {href: "docs/jQuery.getJSON.html", title: "jQuery.getJSON()",
        description: "Load JSON-encoded data from the server using a GET HTTP request."},
    {href: "docs/jQuery.getScript.html", title: "jQuery.getScript()",
        description: "Load a JavaScript file from the server using a GET HTTP request, then execute it."},
    {href: "docs/jQuery.globalEval.html", title: "jQuery.globalEval()",
        description: "Execute some JavaScript code globally."},
    {href: "docs/jQuery.grep.html", title: "jQuery.grep()",
        description: "Finds the elements of an array which satisfy a filter function. The original array is not affected."},
    {href: "docs/jQuery.hasData.html", title: "jQuery.hasData()",
        description: "Determine whether an element has any jQuery data associated with it."},
    {href: "docs/jQuery.holdReady.html", title: "jQuery.holdReady()",
        description: "Holds or releases the execution of jQuery’s ready event."},
    {href: "docs/jQuery.inArray.html", title: "jQuery.inArray()",
        description: "Search for a specified value within an array and return its index (or -1 if not found)."},
    {href: "docs/jQuery.isArray.html", title: "jQuery.isArray()",
        description: "Determine whether the argument is an array."},
    {href: "docs/jQuery.isEmptyObject.html", title: "jQuery.isEmptyObject()",
        description: "Check to see if an object is empty (contains no enumerable properties)."},
    {href: "docs/jQuery.isFunction.html", title: "jQuery.isFunction()",
        description: "Determine if the argument passed is a Javascript function object."},
    {href: "docs/jQuery.isNumeric.html", title: "jQuery.isNumeric()",
        description: "Determines whether its argument is a number."},
    {href: "docs/jQuery.isPlainObject.html", title: "jQuery.isPlainObject()",
        description: "Check to see if an object is a plain object (created using “{}” or “new Object”)."},
    {href: "docs/jQuery.isWindow.html", title: "jQuery.isWindow()",
        description: "Determine whether the argument is a window."},
    {href: "docs/jQuery.isXMLDoc.html", title: "jQuery.isXMLDoc()",
        description: "Check to see if a DOM node is within an XML document (or is an XML document)."},
    {href: "docs/jQuery.makeArray.html", title: "jQuery.makeArray()",
        description: "Convert an array-like object into a true JavaScript array."},
    {href: "docs/jQuery.map.html", title: "jQuery.map()",
        description: "Translate all items in an array or object to new array of items."},
    {href: "docs/jQuery.merge.html", title: "jQuery.merge()",
        description: "Merge the contents of two arrays together into the first array."},
    {href: "docs/jQuery.noConflict.html", title: "jQuery.noConflict()",
        description: "Relinquish jQuery’s control of the $ variable."},
    {href: "docs/jQuery.noop.html", title: "jQuery.noop()",
        description: "An empty function."},
    {href: "docs/jQuery.now.html", title: "jQuery.now()",
        description: "Return a number representing the current time."},
    {href: "docs/jQuery.param.html", title: "jQuery.param()",
        description: "Create a serialized representation of an array or object, suitable for use in a URL query string or Ajax request."},
    {href: "docs/jQuery.parseHTML.html", title: "jQuery.parseHTML()",
        description: "Parses a string into an array of DOM nodes."},
    {href: "docs/jQuery.parseJSON.html", title: "jQuery.parseJSON()",
        description: "Takes a well-formed JSON string and returns the resulting JavaScript object."},
    {href: "docs/jQuery.parseXML.html", title: "jQuery.parseXML()",
        description: "Parses a string into an XML document."},
    {href: "docs/jQuery.post.html", title: "jQuery.post()",
        description: "Load data from the server using a HTTP POST request."},
    {href: "docs/jQuery.proxy.html", title: "jQuery.proxy()",
        description: "Takes a function and returns a new one that will always have a particular context."},
    {href: "docs/jQuery.queue.html", title: "jQuery.queue()",
        description: "Show or manipulate the queue of functions to be executed on the matched element."},
    {href: "docs/jQuery.removeData.html", title: "jQuery.removeData()",
        description: "Remove a previously-stored piece of data."},
    {href: "docs/jQuery.sub.html", title: "jQuery.sub()",
        description: "Creates a new copy of jQuery whose properties and methods can be modified without affecting the original jQuery object."},
    {href: "docs/jQuery.support.html", title: "jQuery.support",
        description: "A collection of properties that represent the presence of different browser features or bugs. Intended for jQuery’s internal use; specific properties may be removed when they are no longer needed internally to improve page startup performance. For your own project’s feature-detection needs, we strongly recommend the use of an external library such as Modernizr instead of dependency on properties in jQuery.support."},
    {href: "docs/jQuery.trim.html", title: "jQuery.trim()",
        description: "Remove the whitespace from the beginning and end of a string."},
    {href: "docs/jQuery.type.html", title: "jQuery.type()",
        description: "Determine the internal JavaScript [[Class]] of an object."},
    {href: "docs/jQuery.unique.html", title: "jQuery.unique()",
        description: "Sorts an array of DOM elements, in place, with the duplicates removed. Note that this only works on arrays of DOM elements, not strings or numbers."},
    {href: "docs/jQuery.when.html", title: "jQuery.when()",
        description: "Provides a way to execute callback functions based on one or more objects, usually Deferred objects that represent asynchronous events."},
    {href: "docs/keydown.html", title: ".keydown()",
        description: "Bind an event handler to the “keydown” JavaScript event, or trigger that event on an element."},
    {href: "docs/keypress.html", title: ".keypress()",
        description: "Bind an event handler to the “keypress” JavaScript event, or trigger that event on an element."},
    {href: "docs/keyup.html", title: ".keyup()",
        description: "Bind an event handler to the “keyup” JavaScript event, or trigger that event on an element."},
    {href: "docs/lang-selector.html", title: ":lang() Selector",
        description: "Selects all elements of the specified language."},
    {href: "docs/last.html", title: ".last()",
        description: "Reduce the set of matched elements to the final one in the set."},
    {href: "docs/last-child-selector.html", title: ":last-child Selector",
        description: "Selects all elements that are the last child of their parent."},
    {href: "docs/last-of-type-selector.html", title: ":last-of-type Selector",
        description: "Selects all elements that are the last among siblings of the same element name."},
    {href: "docs/last-selector.html", title: ":last Selector",
        description: "Selects the last matched element."},
    {href: "docs/length.html", title: ".length",
        description: "The number of elements in the jQuery object."},
    {href: "docs/live.html", title: ".live()",
        description: "Attach an event handler for all elements which match the current selector, now and in the future."},
    {href: "docs/load.html", title: ".load()",
        description: "Load data from the server and place the returned HTML into the matched element."},
    {href: "docs/load-event.html", title: ".load()",
        description: "Bind an event handler to the “load” JavaScript event."},
    {href: "docs/lt-selector.html", title: ":lt() Selector",
        description: "Select all elements at an index less than index within the matched set."},
    {href: "docs/map.html", title: ".map()",
        description: "Pass each element in the current matched set through a function, producing a new jQuery object containing the return values."},
    {href: "docs/mousedown.html", title: ".mousedown()",
        description: "Bind an event handler to the “mousedown” JavaScript event, or trigger that event on an element."},
    {href: "docs/mouseenter.html", title: ".mouseenter()",
        description: "Bind an event handler to be fired when the mouse enters an element, or trigger that handler on an element."},
    {href: "docs/mouseleave.html", title: ".mouseleave()",
        description: "Bind an event handler to be fired when the mouse leaves an element, or trigger that handler on an element."},
    {href: "docs/mousemove.html", title: ".mousemove()",
        description: "Bind an event handler to the “mousemove” JavaScript event, or trigger that event on an element."},
    {href: "docs/mouseout.html", title: ".mouseout()",
        description: "Bind an event handler to the “mouseout” JavaScript event, or trigger that event on an element."},
    {href: "docs/mouseover.html", title: ".mouseover()",
        description: "Bind an event handler to the “mouseover” JavaScript event, or trigger that event on an element."},
    {href: "docs/mouseup.html", title: ".mouseup()",
        description: "Bind an event handler to the “mouseup” JavaScript event, or trigger that event on an element."},
    {href: "docs/multiple-attribute-selector.html", title: "Multiple Attribute Selector [name=&quot;value&quot;][name2=&quot;value2&quot;]",
        description: "Matches elements that match all of the specified attribute filters."},
    {href: "docs/multiple-selector.html", title: "Multiple Selector (“selector1, selector2, selectorN”)",
        description: "Selects the combined results of all the specified selectors."},
    {href: "docs/next.html", title: ".next()",
        description: "Get the immediately following sibling of each element in the set of matched elements. If a selector is provided, it retrieves the next sibling only if it matches that selector."},
    {href: "docs/next-adjacent-Selector.html", title: "Next Adjacent Selector (“prev + next”)",
        description: "Selects all next elements matching “next” that are immediately preceded by a sibling “prev”."},
    {href: "docs/next-siblings-selector.html", title: "Next Siblings Selector (“prev ~ siblings”)",
        description: "Selects all sibling elements that follow after the “prev” element, have the same parent, and match the filtering “siblings” selector."},
    {href: "docs/nextAll.html", title: ".nextAll()",
        description: "Get all following siblings of each element in the set of matched elements, optionally filtered by a selector."},
    {href: "docs/nextUntil.html", title: ".nextUntil()",
        description: "Get all following siblings of each element up to but not including the element matched by the selector, DOM node, or jQuery object passed."},
    {href: "docs/not.html", title: ".not()",
        description: "Remove elements from the set of matched elements."},
    {href: "docs/not-selector.html", title: ":not() Selector",
        description: "Selects all elements that do not match the given selector."},
    {href: "docs/nth-child-selector.html", title: ":nth-child() Selector",
        description: "Selects all elements that are the nth-child of their parent."},
    {href: "docs/nth-last-child-selector.html", title: ":nth-last-child() Selector",
        description: "Selects all elements that are the nth-child of their parent, counting from the last element to the first."},
    {href: "docs/nth-last-of-type-selector.html", title: ":nth-last-of-type() Selector",
        description: "Selects all elements that are the nth-child of their parent, counting from the last element to the first."},
    {href: "docs/nth-of-type-selector.html", title: ":nth-of-type() Selector",
        description: "Selects all elements that are the nth child of their parent in relation to siblings with the same element name."},
    {href: "docs/odd-selector.html", title: ":odd Selector",
        description: "Selects odd elements, zero-indexed.  See also even."},
    {href: "docs/off.html", title: ".off()",
        description: "Remove an event handler."},
    {href: "docs/offset.html", title: ".offset()",
        description: "Get the current coordinates of the first element, or set the coordinates of every element, in the set of matched elements, relative to the document."},
    {href: "docs/offsetParent.html", title: ".offsetParent()",
        description: "Get the closest ancestor element that is positioned."},
    {href: "docs/on.html", title: ".on()",
        description: "Attach an event handler function for one or more events to the selected elements."},
    {href: "docs/one.html", title: ".one()",
        description: "Attach a handler to an event for the elements. The handler is executed at most once per element per event type."},
    {href: "docs/only-child-selector.html", title: ":only-child Selector",
        description: "Selects all elements that are the only child of their parent."},
    {href: "docs/only-of-type-selector.html", title: ":only-of-type Selector",
        description: "Selects all elements that have no siblings with the same element name."},
    {href: "docs/outerHeight.html", title: ".outerHeight()",
        description: "Get the current computed height for the first element in the set of matched elements, including padding, border, and optionally margin. Returns a number (without “px”) representation of the value or null if called on an empty set of elements."},
    {href: "docs/outerWidth.html", title: ".outerWidth()",
        description: "Get the current computed width for the first element in the set of matched elements, including padding and border."},
    {href: "docs/parent.html", title: ".parent()",
        description: "Get the parent of each element in the current set of matched elements, optionally filtered by a selector."},
    {href: "docs/parent-selector.html", title: ":parent Selector",
        description: "Select all elements that have at least one child node (either an element or text)."},
    {href: "docs/parents.html", title: ".parents()",
        description: "Get the ancestors of each element in the current set of matched elements, optionally filtered by a selector."},
    {href: "docs/parentsUntil.html", title: ".parentsUntil()",
        description: "Get the ancestors of each element in the current set of matched elements, up to but not including the element matched by the selector, DOM node, or jQuery object."},
    {href: "docs/password-selector.html", title: ":password Selector",
        description: "Selects all elements of type password."},
    {href: "docs/position.html", title: ".position()",
        description: "Get the current coordinates of the first element in the set of matched elements, relative to the offset parent."},
    {href: "docs/prepend.html", title: ".prepend()",
        description: "Insert content, specified by the parameter, to the beginning of each element in the set of matched elements."},
    {href: "docs/prependTo.html", title: ".prependTo()",
        description: "Insert every element in the set of matched elements to the beginning of the target."},
    {href: "docs/prev.html", title: ".prev()",
        description: "Get the immediately preceding sibling of each element in the set of matched elements, optionally filtered by a selector."},
    {href: "docs/prevAll.html", title: ".prevAll()",
        description: "Get all preceding siblings of each element in the set of matched elements, optionally filtered by a selector."},
    {href: "docs/prevUntil.html", title: ".prevUntil()",
        description: "Get all preceding siblings of each element up to but not including the element matched by the selector, DOM node, or jQuery object."},
    {href: "docs/promise.html", title: ".promise()",
        description: "Return a Promise object to observe when all actions of a certain type bound to the collection, queued or not, have finished."},
    {href: "docs/prop.html", title: ".prop()",
        description: "Get the value of a property for the first element in the set of matched elements or set one or more properties for every matched element."},
    {href: "docs/pushStack.html", title: ".pushStack()",
        description: "Add a collection of DOM elements onto the jQuery stack."},
    {href: "docs/queue.html", title: ".queue()",
        description: "Show or manipulate the queue of functions to be executed on the matched elements."},
    {href: "docs/radio-selector.html", title: ":radio Selector",
        description: "Selects all  elements of type radio."},
    {href: "docs/ready.html", title: ".ready()",
        description: "Specify a function to execute when the DOM is fully loaded."},
    {href: "docs/remove.html", title: ".remove()",
        description: "Remove the set of matched elements from the DOM."},
    {href: "docs/removeAttr.html", title: ".removeAttr()",
        description: "Remove an attribute from each element in the set of matched elements."},
    {href: "docs/removeClass.html", title: ".removeClass()",
        description: "Remove a single class, multiple classes, or all classes from each element in the set of matched elements."},
    {href: "docs/removeData.html", title: ".removeData()",
        description: "Remove a previously-stored piece of data."},
    {href: "docs/removeProp.html", title: ".removeProp()",
        description: "Remove a property for the set of matched elements."},
    {href: "docs/replaceAll.html", title: ".replaceAll()",
        description: "Replace each target element with the set of matched elements."},
    {href: "docs/replaceWith.html", title: ".replaceWith()",
        description: "Replace each element in the set of matched elements with the provided new content and return the set of elements that was removed."},
    {href: "docs/reset-selector.html", title: ":reset Selector",
        description: "Selects all elements of type reset."},
    {href: "docs/resize.html", title: ".resize()",
        description: "Bind an event handler to the “resize” JavaScript event, or trigger that event on an element."},
    {href: "docs/root-selector.html", title: ":root Selector",
        description: "Selects the element that is the root of the document."},
    {href: "docs/scroll.html", title: ".scroll()",
        description: "Bind an event handler to the “scroll” JavaScript event, or trigger that event on an element."},
    {href: "docs/scrollLeft.html", title: ".scrollLeft()",
        description: "Get the current horizontal position of the scroll bar for the first element in the set of matched elements or set the horizontal position of the scroll bar for every matched element."},
    {href: "docs/scrollTop.html", title: ".scrollTop()",
        description: "Get the current vertical position of the scroll bar for the first element in the set of matched elements or set the vertical position of the scroll bar for every matched element."},
    {href: "docs/select.html", title: ".select()",
        description: "Bind an event handler to the “select” JavaScript event, or trigger that event on an element."},
    {href: "docs/selected-selector.html", title: ":selected Selector",
        description: "Selects all elements that are selected."},
    {href: "docs/selector.html", title: ".selector",
        description: "A selector representing selector passed to jQuery(), if any, when creating the original set."},
    {href: "docs/serialize.html", title: ".serialize()",
        description: "Encode a set of form elements as a string for submission."},
    {href: "docs/serializeArray.html", title: ".serializeArray()",
        description: "Encode a set of form elements as an array of names and values."},
    {href: "docs/show.html", title: ".show()",
        description: "Display the matched elements."},
    {href: "docs/siblings.html", title: ".siblings()",
        description: "Get the siblings of each element in the set of matched elements, optionally filtered by a selector."},
    {href: "docs/size.html", title: ".size()",
        description: "Return the number of elements in the jQuery object."},
    {href: "docs/slice.html", title: ".slice()",
        description: "Reduce the set of matched elements to a subset specified by a range of indices."},
    {href: "docs/slideDown.html", title: ".slideDown()",
        description: "Display the matched elements with a sliding motion."},
    {href: "docs/slideToggle.html", title: ".slideToggle()",
        description: "Display or hide the matched elements with a sliding motion."},
    {href: "docs/slideUp.html", title: ".slideUp()",
        description: "Hide the matched elements with a sliding motion."},
    {href: "docs/stop.html", title: ".stop()",
        description: "Stop the currently-running animation on the matched elements."},
    {href: "docs/submit.html", title: ".submit()",
        description: "Bind an event handler to the “submit” JavaScript event, or trigger that event on an element."},
    {href: "docs/submit-selector.html", title: ":submit Selector",
        description: "Selects all elements of type submit."},
    {href: "docs/target-selector.html", title: ":target Selector",
        description: "Selects the target element indicated by the fragment identifier of the document’s URI."},
    {href: "docs/text.html", title: ".text()",
        description: "Get the combined text contents of each element in the set of matched elements, including their descendants, or set the text contents of the matched elements."},
    {href: "docs/text-selector.html", title: ":text Selector",
        description: "Selects all elements of type text."},
    {href: "docs/toArray.html", title: ".toArray()",
        description: "Retrieve all the elements contained in the jQuery set, as an array."},
    {href: "docs/toggle.html", title: ".toggle()",
        description: "Display or hide the matched elements."},
    {href: "docs/toggle-event.html", title: ".toggle()",
        description: "Bind two or more handlers to the matched elements, to be executed on alternate clicks."},
    {href: "docs/toggleClass.html", title: ".toggleClass()",
        description: "Add or remove one or more classes from each element in the set of matched elements, depending on either the class’s presence or the value of the switch argument."},
    {href: "docs/trigger.html", title: ".trigger()",
        description: "Execute all handlers and behaviors attached to the matched elements for the given event type."},
    {href: "docs/triggerHandler.html", title: ".triggerHandler()",
        description: "Execute all handlers attached to an element for an event."},
    {href: "docs/unbind.html", title: ".unbind()",
        description: "Remove a previously-attached event handler from the elements."},
    {href: "docs/undelegate.html", title: ".undelegate()",
        description: "Remove a handler from the event for all elements which match the current selector, based upon a specific set of root elements."},
    {href: "docs/unload.html", title: ".unload()",
        description: "Bind an event handler to the “unload” JavaScript event."},
    {href: "docs/unwrap.html", title: ".unwrap()",
        description: "Remove the parents of the set of matched elements from the DOM, leaving the matched elements in their place."},
    {href: "docs/val.html", title: ".val()",
        description: "Get the current value of the first element in the set of matched elements or set the value of every matched element."},
    {href: "docs/visible-selector.html", title: ":visible Selector",
        description: "Selects all elements that are visible."},
    {href: "docs/width.html", title: ".width()",
        description: "Get the current computed width for the first element in the set of matched elements or set the width of every matched element."},
    {href: "docs/wrap.html", title: ".wrap()",
        description: "Wrap an HTML structure around each element in the set of matched elements."},
    {href: "docs/wrapAll.html", title: ".wrapAll()",
        description: "Wrap an HTML structure around all elements in the set of matched elements."},
    {href: "docs/wrapInner.html", title: ".wrapInner()",
        description: "Wrap an HTML structure around the content of each element in the set of matched elements."}
];
